version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mensajes
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 1234
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - spring_network

networks:
  spring_network:

volumes:
  mysql_data:
